# Generated by Django 3.1.3 on 2020-11-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebelier',
            name='image',
            field=models.ImageField(max_length=254, upload_to='media/photos'),
        ),
    ]
