# Generated by Django 3.1.3 on 2020-11-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20201114_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebelier',
            name='image',
            field=models.ImageField(max_length=254, upload_to='photos'),
        ),
    ]
