# Generated by Django 3.1.3 on 2020-11-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20201114_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagebelier',
            name='category',
            field=models.CharField(choices=[('CH', 'chambres'), ('PA', 'partenaires')], default='CH', max_length=2),
        ),
    ]
