# Generated by Django 3.1.3 on 2020-11-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_imagebelier_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebelier',
            name='category',
            field=models.CharField(choices=[('HO', 'photo principal'), ('MA', 'photo contenu'), ('PA', 'partenaires')], default='MA', max_length=2),
        ),
    ]
