# Generated by Django 3.1.3 on 2020-11-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_imagebelier_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagebelier',
            name='image_64',
            field=models.TextField(blank=True),
        ),
    ]
