# Generated by Django 3.1.3 on 2020-11-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_imagebelier_image_64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebelier',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='photos'),
        ),
    ]
