# Generated by Django 3.1.3 on 2020-11-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20201117_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebelier',
            name='category',
            field=models.CharField(default='comp-portrait', max_length=200),
        ),
    ]
